AWSTemplateFormatVersion: "2010-09-09"
Description: "Health Platform — Kinesis Data Stream"

Parameters:
  Environment:
    Type: String
    Default: poc
  ShardCount:
    Type: Number
    Default: 2
  RetentionHours:
    Type: Number
    Default: 24

Resources:
  HealthEventsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub "${Environment}-health-platform-events"
      ShardCount: !Ref ShardCount
      RetentionPeriodHours: !Ref RetentionHours
      StreamEncryption:
        EncryptionType: KMS
        KeyId: alias/aws/kinesis

Outputs:
  StreamName:
    Value: !Ref HealthEventsStream
    Export: { Name: !Sub "${Environment}-StreamName" }
  StreamArn:
    Value: !GetAtt HealthEventsStream.Arn
    Export: { Name: !Sub "${Environment}-StreamArn" }
